import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import ProductList from "../components/ProductList";
import TransactionList from "../components/TransactionList";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isActive={true}>
        <div className="flex justify-between">
          <ProductList />
          <TransactionList />
        </div>
      </Layout>
    </div>
  );
};

export default Home;
